spring.application.name=TROYA_STATISTICS_SUSTAINABILITY_BACKEND


spring.data.mongodb.uri=mongodb+srv://SantiagoS:pUffphbfRtxZynWA@baseproyecto.h5zdq2x.mongodb.net/TroyaStatistics

spring.rabbitmq.host=leopard-01.lmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=nuhzhoqx
spring.rabbitmq.password=jI-0Mqey5aHZ9KU1_L49tOUxENpSkDfV
spring.rabbitmq.virtual-host=nuhzhoqx

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
